// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package logpushjob

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-cloudflare.logpushJob.LogpushJob",
		reflect.TypeOf((*LogpushJob)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "accountId", GoGetter: "AccountId"},
			_jsii_.MemberProperty{JsiiProperty: "accountIdInput", GoGetter: "AccountIdInput"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dataset", GoGetter: "Dataset"},
			_jsii_.MemberProperty{JsiiProperty: "datasetInput", GoGetter: "DatasetInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "destinationConf", GoGetter: "DestinationConf"},
			_jsii_.MemberProperty{JsiiProperty: "destinationConfInput", GoGetter: "DestinationConfInput"},
			_jsii_.MemberProperty{JsiiProperty: "enabled", GoGetter: "Enabled"},
			_jsii_.MemberProperty{JsiiProperty: "enabledInput", GoGetter: "EnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "filter", GoGetter: "Filter"},
			_jsii_.MemberProperty{JsiiProperty: "filterInput", GoGetter: "FilterInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "frequency", GoGetter: "Frequency"},
			_jsii_.MemberProperty{JsiiProperty: "frequencyInput", GoGetter: "FrequencyInput"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "kind", GoGetter: "Kind"},
			_jsii_.MemberProperty{JsiiProperty: "kindInput", GoGetter: "KindInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "logpullOptions", GoGetter: "LogpullOptions"},
			_jsii_.MemberProperty{JsiiProperty: "logpullOptionsInput", GoGetter: "LogpullOptionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxUploadBytes", GoGetter: "MaxUploadBytes"},
			_jsii_.MemberProperty{JsiiProperty: "maxUploadBytesInput", GoGetter: "MaxUploadBytesInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxUploadIntervalSeconds", GoGetter: "MaxUploadIntervalSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "maxUploadIntervalSecondsInput", GoGetter: "MaxUploadIntervalSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxUploadRecords", GoGetter: "MaxUploadRecords"},
			_jsii_.MemberProperty{JsiiProperty: "maxUploadRecordsInput", GoGetter: "MaxUploadRecordsInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "outputOptions", GoGetter: "OutputOptions"},
			_jsii_.MemberProperty{JsiiProperty: "outputOptionsInput", GoGetter: "OutputOptionsInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "ownershipChallenge", GoGetter: "OwnershipChallenge"},
			_jsii_.MemberProperty{JsiiProperty: "ownershipChallengeInput", GoGetter: "OwnershipChallengeInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putOutputOptions", GoMethod: "PutOutputOptions"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccountId", GoMethod: "ResetAccountId"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnabled", GoMethod: "ResetEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetFilter", GoMethod: "ResetFilter"},
			_jsii_.MemberMethod{JsiiMethod: "resetFrequency", GoMethod: "ResetFrequency"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetKind", GoMethod: "ResetKind"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogpullOptions", GoMethod: "ResetLogpullOptions"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxUploadBytes", GoMethod: "ResetMaxUploadBytes"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxUploadIntervalSeconds", GoMethod: "ResetMaxUploadIntervalSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxUploadRecords", GoMethod: "ResetMaxUploadRecords"},
			_jsii_.MemberMethod{JsiiMethod: "resetName", GoMethod: "ResetName"},
			_jsii_.MemberMethod{JsiiMethod: "resetOutputOptions", GoMethod: "ResetOutputOptions"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetOwnershipChallenge", GoMethod: "ResetOwnershipChallenge"},
			_jsii_.MemberMethod{JsiiMethod: "resetZoneId", GoMethod: "ResetZoneId"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "zoneId", GoGetter: "ZoneId"},
			_jsii_.MemberProperty{JsiiProperty: "zoneIdInput", GoGetter: "ZoneIdInput"},
		},
		func() interface{} {
			j := jsiiProxy_LogpushJob{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-cloudflare.logpushJob.LogpushJobConfig",
		reflect.TypeOf((*LogpushJobConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-cloudflare.logpushJob.LogpushJobOutputOptions",
		reflect.TypeOf((*LogpushJobOutputOptions)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-cloudflare.logpushJob.LogpushJobOutputOptionsOutputReference",
		reflect.TypeOf((*LogpushJobOutputOptionsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "batchPrefix", GoGetter: "BatchPrefix"},
			_jsii_.MemberProperty{JsiiProperty: "batchPrefixInput", GoGetter: "BatchPrefixInput"},
			_jsii_.MemberProperty{JsiiProperty: "batchSuffix", GoGetter: "BatchSuffix"},
			_jsii_.MemberProperty{JsiiProperty: "batchSuffixInput", GoGetter: "BatchSuffixInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "cve20214428", GoGetter: "Cve20214428"},
			_jsii_.MemberProperty{JsiiProperty: "cve20214428Input", GoGetter: "Cve20214428Input"},
			_jsii_.MemberProperty{JsiiProperty: "fieldDelimiter", GoGetter: "FieldDelimiter"},
			_jsii_.MemberProperty{JsiiProperty: "fieldDelimiterInput", GoGetter: "FieldDelimiterInput"},
			_jsii_.MemberProperty{JsiiProperty: "fieldNames", GoGetter: "FieldNames"},
			_jsii_.MemberProperty{JsiiProperty: "fieldNamesInput", GoGetter: "FieldNamesInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "outputType", GoGetter: "OutputType"},
			_jsii_.MemberProperty{JsiiProperty: "outputTypeInput", GoGetter: "OutputTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "recordDelimiter", GoGetter: "RecordDelimiter"},
			_jsii_.MemberProperty{JsiiProperty: "recordDelimiterInput", GoGetter: "RecordDelimiterInput"},
			_jsii_.MemberProperty{JsiiProperty: "recordPrefix", GoGetter: "RecordPrefix"},
			_jsii_.MemberProperty{JsiiProperty: "recordPrefixInput", GoGetter: "RecordPrefixInput"},
			_jsii_.MemberProperty{JsiiProperty: "recordSuffix", GoGetter: "RecordSuffix"},
			_jsii_.MemberProperty{JsiiProperty: "recordSuffixInput", GoGetter: "RecordSuffixInput"},
			_jsii_.MemberProperty{JsiiProperty: "recordTemplate", GoGetter: "RecordTemplate"},
			_jsii_.MemberProperty{JsiiProperty: "recordTemplateInput", GoGetter: "RecordTemplateInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetBatchPrefix", GoMethod: "ResetBatchPrefix"},
			_jsii_.MemberMethod{JsiiMethod: "resetBatchSuffix", GoMethod: "ResetBatchSuffix"},
			_jsii_.MemberMethod{JsiiMethod: "resetCve20214428", GoMethod: "ResetCve20214428"},
			_jsii_.MemberMethod{JsiiMethod: "resetFieldDelimiter", GoMethod: "ResetFieldDelimiter"},
			_jsii_.MemberMethod{JsiiMethod: "resetFieldNames", GoMethod: "ResetFieldNames"},
			_jsii_.MemberMethod{JsiiMethod: "resetOutputType", GoMethod: "ResetOutputType"},
			_jsii_.MemberMethod{JsiiMethod: "resetRecordDelimiter", GoMethod: "ResetRecordDelimiter"},
			_jsii_.MemberMethod{JsiiMethod: "resetRecordPrefix", GoMethod: "ResetRecordPrefix"},
			_jsii_.MemberMethod{JsiiMethod: "resetRecordSuffix", GoMethod: "ResetRecordSuffix"},
			_jsii_.MemberMethod{JsiiMethod: "resetRecordTemplate", GoMethod: "ResetRecordTemplate"},
			_jsii_.MemberMethod{JsiiMethod: "resetSampleRate", GoMethod: "ResetSampleRate"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimestampFormat", GoMethod: "ResetTimestampFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "sampleRate", GoGetter: "SampleRate"},
			_jsii_.MemberProperty{JsiiProperty: "sampleRateInput", GoGetter: "SampleRateInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "timestampFormat", GoGetter: "TimestampFormat"},
			_jsii_.MemberProperty{JsiiProperty: "timestampFormatInput", GoGetter: "TimestampFormatInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_LogpushJobOutputOptionsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
